---

- name: "configuration play." 
  hosts: web
  user: ubuntu
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  pre_tasks:
    - name: Wait 300 seconds, but only start checking after 60 seconds
      wait_for_connection:
        delay: 60
        timeout: 300

    - name: "update apt packages."
      become: yes
      apt:
        update_cache: yes

    - name: "upgrade packages"
      become: yes
      apt:
        upgrade: yes

    - name: "install nodejs"
      become: yes
      apt:
        name: ["nodejs"]
        state: latest

    - name: "install npm"
      become: yes
      apt:
        name: ["npm"]
        state: latest

    - name: "install pm2"
      become: yes
      shell: npm install pm2 -g



#  roles:
#    - configure-server
#    - configure-prometheus-node-exporter
