---

- name: "configuration play." 
  hosts: web
  user: ubuntu
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  environment:
    ENVIRONMENT: production
    TYPEORM_CONNECTION: postgres
    TYPEORM_ENTITIES: ./src/modules/domain/**/*.entity.ts
    TYPEORM_HOST: Todo {your postgres database hostname in RDS}
    TYPEORM_PORT: 5532 #(or the port from RDS if it’s different)
    TYPEORM_USERNAME: todo #{your postgres database username in RDS}
    TYPEORM_PASSWORD: todo #{your postgres database password in RDS}
    TYPEORM_DATABASE: todo #{your postgres database name in RDS}

  pre_tasks:
    - name: Wait 300 seconds, but only start checking after 60 seconds
      wait_for_connection:
        delay: 60
        timeout: 300

    - name: "update apt packages."
      become: yes
      apt:
        update_cache: yes

    - name: "upgrade packages"
      become: yes
      apt:
        upgrade: yes

    - name: "install nodejs"
      become: yes
      apt:
        name: ["nodejs"]
        state: latest

    - name: "install npm"
      become: yes
      apt:
        name: ["npm"]
        state: latest

    - name: "install pm2"
      become: yes
      shell: npm install pm2 -g


  roles:
    - configure-server
    - configure-prometheus-node-exporter
