- name: "create directory"
  file:
    path: ~/udacity
    state: directory

- name: "copy files"
  copy:
    src: "{{ role_path }}/../../../../backend"
    dest: ~/udacity

- name: "install dependencies from package"
  shell: cd ~/udacity/backend; npm i

- name: "build backend"
  shell: cd ~/udacity/backend; npm run build

